version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres # Nome do serviço do PostgreSQL no EasyPanel
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: unless-stopped
